require('./_build/default/main.bc.js');
const L = globalThis.SanctaphraxLib;
const retail = { perSeCategory: { kind: 'NotPerSeProfessional' }, largeUndertakingData: { balanceSheetTotal: 0, netTurnover: 0, ownFunds: 0 }, hasRequestedProfessionalTreatment: false, firmHasAssessedExpertise: false };
const wii = (o) => L.wellInformedInvestorStatus({ investorIn: { mifidProfile: retail, isInstitutionalInvestor: false, hasWrittenAdherence: false, investmentAmount: 0, hasExpertiseAssessment: false, isInvolvedInManagement: false, ...o } });
const pro = (o) => L.professionalInvestorStatus({ investorIn: { ...retail, ...o } });
let failed = 0;
const check = (name, got, want) => { const ok = got === want; if (!ok) failed++; console.log(ok ? 'ok  ' : 'FAIL', name, '->', got); };
check('adherence + 100k exact', wii({ hasWrittenAdherence: true, investmentAmount: 100000 }).isWellInformed, true);
check('adherence + 99999.99', wii({ hasWrittenAdherence: true, investmentAmount: 99999.99 }).isWellInformed, false);
check('500k+assessment, no adherence', wii({ investmentAmount: 500000, hasExpertiseAssessment: true }).isWellInformed, false);
check('adherence + assessment only', wii({ hasWrittenAdherence: true, hasExpertiseAssessment: true }).isWellInformed, true);
check('institutional', wii({ isInstitutionalInvestor: true }).isWellInformed, true);
const d = wii({ isInvolvedInManagement: true });
check('director not well-informed', d.isWellInformed, false);
check('director may invest', d.mayInvest, true);
check('per-se credit inst', pro({ perSeCategory: { kind: 'CreditInstitution' } }).isProfessional, true);
check('large undertaking 2/3', pro({ largeUndertakingData: { balanceSheetTotal: 25000000, netTurnover: 50000000, ownFunds: 0 } }).isProfessional, true);
check('large undertaking 1/3', pro({ largeUndertakingData: { balanceSheetTotal: 25000000, netTurnover: 0, ownFunds: 0 } }).isProfessional, false);
check('elective', pro({ hasRequestedProfessionalTreatment: true, firmHasAssessedExpertise: true }).isProfessional, true);
check('retail', pro({}).isProfessional, false);
console.log(failed ? `${failed} FAILED` : 'ALL 12 PASS');
process.exit(failed ? 1 : 0);
